#!/usr/bin/python
import zipfile, os, sys
if not os.path.exists('EXTRACTED'):
    z = zipfile.ZipFile('streamer.zip', 'r')
    z.extractall('.')
    z.close()
    with open('EXTRACTED', 'wb') as out:
        out.write('yes')

from hosted import config
config.restart_on_update()

import time, traceback, threading
from Queue import Queue
from ibquery import InfoBeamerQuery

def run_in_thread(fn):
    def loop():
        while 1:
            try:
                fn()
            except:
                print >>sys.stderr, "error in %r. retrying"
                traceback.print_exc()
                time.sleep(1)
    t = threading.Thread(target=loop)
    t.daemon = True
    t.start()

q = Queue()

def channel_monitor():
    ib = InfoBeamerQuery('127.0.0.1')
    con = ib.node("root").io(raw=True)

    for line in con:
        stream_url = line.strip()
        if stream_url:
            q.put(stream_url)
            break

    for line in con:
        now_url = line.strip()
        if now_url != stream_url:
            break
    os.kill(os.getpid(), 9)

run_in_thread(channel_monitor)

def start_stream(url):
    while len(sys.argv) > 1:
        sys.argv.pop()
    sys.argv.extend([
        "--player-external-http",
        "--player-external-http-port", "8000",
        url, "best",
    ])
    print >>sys.stderr, sys.argv
    from streamlink_cli.main import main
    main()

stream_url = q.get()
start_stream(stream_url)
